[package]
name = "sysbox"
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
moto-runtime = { path = "../../lib/moto-runtime", features = ["rt-api"] }
moto-ipc     = { path = "../../lib/moto-ipc"    }
moto-sys     = { path = "../../lib/moto-sys"    }
moto-sys-io  = { path = "../../lib/moto-sys-io" }
time = { version = "0.3.36", default-features = false, features = ["std"] }

