[package]
name = "imager"
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
flatfs = { path = "../sys/lib/flatfs" }
srfs   = { path = "../sys/lib/srfs"   }
mbrman = "0.5.2"

